version: '3'
services:
  spring-boot-angular-template:
    image: docker.pkg.github.com/mrrobworks/spring-boot-angular-template/spring-boot-angular-template:0.2-SNAPSHOT
    container_name: spring-boot-angular-template-service
    volumes:
      - ./wait-for.sh:/tmp/wait-for.sh
    command: ["sh", "./wait-for.sh", "db:5432", "-t", "20", "--", "java", "-jar", "-Dspring.profiles.active=ref", "app.jar"]
    environment:
      GOOGLE_CLIENT_ID: [google-client-id]
      GOOGLE_CLIENT_SECRET: [google-client-secret]
      GITHUB_CLIENT_ID: [github-client-id]
      GITHUB_CLIENT_SECRET: [github-client-secret]
    ports:
      - "8091:8081"
    networks:
      - mynetwork
    depends_on:
      - db
  flyway:
    command: -url=jdbc:postgresql://db:5432/spring_boot_angular_db_ref -schemas=public -user=postgres_ref -password=changeit_ref -connectRetries=60 migrate
  db:
    environment:
      POSTGRES_USER: postgres_ref
      POSTGRES_PASSWORD: changeit_ref
      POSTGRES_DB: spring_boot_angular_db_ref
    ports:
      - "54331:5432"