spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres_dev
    password: changeit_dev
    url: jdbc:postgresql://localhost:54321/spring_boot_angular_db_dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [google-client-id]
            client-secret: [google-client-secret]
            redirect-uri: http://localhost:4200/
          github:
            client-id: [github-client-id]
            client-secret: [github-client-secret]
