spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres_dev
    password: changeit_dev
    url: jdbc:postgresql://localhost:54321/spring_boot_angular_db_dev
google:
  client:
    client-id: [google-client-id]
    client-secret: [google-client-secret]
github:
  client:
    client-id: [github-client-id]
    client-secret: [google-client-secret]
